// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSocxzoelLRNRgsk-kFo-y5ka0F2K-xys',
    appId: '1:992263025803:web:417a7c4c527bda05f7908e',
    messagingSenderId: '992263025803',
    projectId: 'upc-proyects-e6ff1',
    authDomain: 'upc-proyects-e6ff1.firebaseapp.com',
    storageBucket: 'upc-proyects-e6ff1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDimhw2WJMiHxG8r23uMJkQs4wHpYcdiPg',
    appId: '1:992263025803:android:01479a66a0cd0fdbf7908e',
    messagingSenderId: '992263025803',
    projectId: 'upc-proyects-e6ff1',
    storageBucket: 'upc-proyects-e6ff1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuiJts3_C38guAm1gybBEH9p7HYymjiM4',
    appId: '1:992263025803:ios:ae101bd6f563a1e0f7908e',
    messagingSenderId: '992263025803',
    projectId: 'upc-proyects-e6ff1',
    storageBucket: 'upc-proyects-e6ff1.firebasestorage.app',
    iosBundleId: 'com.example.proyectoupc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuiJts3_C38guAm1gybBEH9p7HYymjiM4',
    appId: '1:992263025803:ios:ae101bd6f563a1e0f7908e',
    messagingSenderId: '992263025803',
    projectId: 'upc-proyects-e6ff1',
    storageBucket: 'upc-proyects-e6ff1.firebasestorage.app',
    iosBundleId: 'com.example.proyectoupc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSocxzoelLRNRgsk-kFo-y5ka0F2K-xys',
    appId: '1:992263025803:web:2d7e8320138cea33f7908e',
    messagingSenderId: '992263025803',
    projectId: 'upc-proyects-e6ff1',
    authDomain: 'upc-proyects-e6ff1.firebaseapp.com',
    storageBucket: 'upc-proyects-e6ff1.firebasestorage.app',
  );
}
